# Generated by Django 5.2.17 on 2026-08-07 08:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = sem limite superior', max_digits=10, null=True)),
                ('mode', models.CharField(choices=[('fixed_amount', 'Valor fixo somado (ex: +50 EUR)'), ('multiplier', 'Multiplicador (ex: 1.30 = +30%)')], default='fixed_amount', max_length=20)),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('50'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Faixa de margem',
                'verbose_name_plural': 'Faixas de margem',
                'ordering': ['min_price'],
            },
        ),
    ]
