# Generated by Django 5.2.17 on 2026-08-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_margintier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Quando o cliente aceitou os termos no cadastro (RGPD).', null=True),
        ),
    ]
