# Generated by Django 5.2.17 on 2026-08-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_consent_accepted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTablePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ponto da tabela de preços',
                'verbose_name_plural': 'Tabela de preços',
                'ordering': ['cost'],
            },
        ),
        migrations.DeleteModel(
            name='MarginRule',
        ),
        migrations.DeleteModel(
            name='MarginTier',
        ),
    ]
