# Generated by Django 5.2.17 on 2026-08-12 13:12
# Popula a tabela de preços com os pontos exatos mandados pelo cliente
# (regra_de_precos.md, tabelaPrecosLDC).

from decimal import Decimal

from django.db import migrations

POINTS = [
    (Decimal("10.00"), Decimal("29.00")),
    (Decimal("25.00"), Decimal("50.00")),
    (Decimal("37.40"), Decimal("75.00")),
    (Decimal("50.00"), Decimal("99.00")),
    (Decimal("75.00"), Decimal("129.00")),
    (Decimal("83.00"), Decimal("145.00")),
    (Decimal("100.00"), Decimal("179.00")),
    (Decimal("150.00"), Decimal("254.00")),
    (Decimal("217.00"), Decimal("399.00")),
    (Decimal("300.00"), Decimal("499.00")),
    (Decimal("409.50"), Decimal("699.00")),
    (Decimal("500.00"), Decimal("799.00")),
    (Decimal("600.00"), Decimal("899.00")),
    (Decimal("750.00"), Decimal("999.00")),
    (Decimal("1000.00"), Decimal("1399.00")),
    (Decimal("1275.00"), Decimal("1500.00")),
    (Decimal("1500.00"), Decimal("2199.00")),
    (Decimal("2000.00"), Decimal("2750.00")),
    (Decimal("3000.00"), Decimal("3999.00")),
]


def seed_points(apps, schema_editor):
    PriceTablePoint = apps.get_model("core", "PriceTablePoint")
    for cost, sale_price in POINTS:
        PriceTablePoint.objects.update_or_create(cost=cost, defaults={"sale_price": sale_price})


def remove_points(apps, schema_editor):
    PriceTablePoint = apps.get_model("core", "PriceTablePoint")
    PriceTablePoint.objects.filter(cost__in=[cost for cost, _ in POINTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pricetablepoint_delete_marginrule_delete_margintier'),
    ]

    operations = [
        migrations.RunPython(seed_points, remove_points),
    ]
