# Generated by Django 5.2.17 on 2026-08-12 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_funcionario_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('selected_fields', models.JSONField(blank=True, default=list, help_text='Nomes dos campos de raw_attributes que o cliente escolheu exibir/usar pra esse fornecedor.')),
            ],
            options={
                'verbose_name': 'Fornecedor (catálogo importado)',
                'verbose_name_plural': 'Fornecedores (catálogo importado)',
            },
        ),
        migrations.CreateModel(
            name='ImportedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('raw_attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedProductFitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('variant', models.CharField(blank=True, max_length=150)),
                ('year_range', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='core.importedproduct')),
            ],
            options={
                'indexes': [models.Index(fields=['make', 'model'], name='core_import_make_a4f59e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importedproduct',
            index=models.Index(fields=['supplier', 'active'], name='core_import_supplie_761570_idx'),
        ),
        migrations.AddConstraint(
            model_name='importedproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'external_reference'), name='unique_product_per_supplier'),
        ),
    ]
